on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: CI

jobs:
  release-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.TOKEN }}
          command: manifest
